### ISSUE TITLE
Issues with package-lock.json when stable version is 7.1.7

### ISSUE THREAD

**Issue by kczereczon** [espocrm/ext-template#11]
**Description**
When I try to build extension env with version 7.1.7 npm install errors (integrity checksum) occurs.

**Console output**
```
root@31fffaed265d:/var/www# node build --all
Fetching EspoCRM repository...
  Downloading EspoCRM archive from Github...
  Unzipping...
Installing EspoCRM instance...
  Creating config...
  Npm install...
(node:2129) UnhandledPromiseRejectionWarning: Error: Command failed: npm install
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at buildEspo (/var/www/build.js:215:8)
    at /var/www/build.js:155:9
    at new Promise (<anonymous>)
    at install (/var/www/build.js:148:12)
    at /var/www/build.js:18:15
(node:2129) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2129) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Step to reproduce**
-run `node build --all`

**Comment by kczereczon** [comment]
probably it's issue with espo base because after changing version of espo to 7.0.9 everything works fine

**Comment by yurikuzn** [comment]
try upgrading npm to v8.0 or greater.
